apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tf-runner-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tf-runner-cluster-role
subjects:
- kind: ServiceAccount
  name: tf-runner
  namespace: pulsar-ignition
- kind: ServiceAccount
  name: tf-runner-legacy-stg
  namespace: pulsar-ignition
- kind: ServiceAccount
  name: tf-runner-legacy-prd
  namespace: pulsar-ignition
