apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: kube-system
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: kube-system
      interval: 1m
      version: "v1.14.5"
  releaseName: cert-manager
  targetNamespace: kube-system
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    installCRDs: true
    serviceAccount:
      name: "cert-manager"
    securityContext:
      fsGroup: 1001
    ingressShim:
      defaultIssuerName: "le-clusterissuer"
      defaultIssuerKind: "ClusterIssuer"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-clusterissuer
spec:
  acme:
    email: pulsar.cencommerce@cencosud.cl
    privateKeySecretRef:
      name: le-clusterissuer
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          ingressClassName: kong